version: '3.8'

services:
    cache:
        image: bitnami/redis
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    db:
        image:
            postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: data
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    pgadmin:
        image:
            dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 80:80
        depends_on:
            - db
    client:
        build: client
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./proto:/usr/src/app/proto

