version: '3.8'

services:
    cache:
        image: bitnami/redis
        ports:
            - 6379:6379
        enviroment:
            - ALLOW_EMPTY_PASSWORD=yes

    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        enviroment:
            - POSTGRES_PASSWORD=password
        VOLUMES:

networks:
  network1:
    # Configuración de la red 1

volumes:
  volume1:
    # Configuración del volumen 1